const allAwardsList = [
    'AHS Citizen/Student of the Month',
    'AHS Citizenship Award in English',
    'AHS Citizenship Award in Science',
    'AHS Citizenship Award in Math',
    'AHS Citizenship Award in History',
    'AHS Citizenship Award in World Language',
    'AHS Citizenship Award in FACS',
    'AHS Citizenship Award in Visual/Studio Art',
    'AHS Citizenship Award in Performing Arts',
    'AHS Citizenship Award in Physical Education',
    'AP Scholar',
    'Eagle Scout Rank/Award',
    'Global Competency Certificate',
    'Junior Book Award',
    'Koplik/Adams Scholarship',
    'Math Fair/Expo Award',
    'National Honors Society',
    'National Language Exams (all languages/levels)',
    'National Merit Commended Scholar/Semifinalist/Finalist/Winner',
    'National World Language Honors Society',
    'Relay for Life Captain',
    'Rotary Youth Leadership Award (RYLA)',
    'Science Olympiad Award',
    'Seal of Biliteracy'
]

const allSportsList = [
    "AB Crew/Rowing",
    "Alpine Skiing",
    "Baseball",
    "Basketball, Boys",
    "Basketball, Girls",
    "Cheerleading - Football",
    "Cross Country, Boys",
    "Cross Country, Girls",
    "Dance",
    "Field Hockey",
    "Football",
    "Gymnastics",
    "Golf",
    "Ice Hockey, Boys",
    "Ice Hockey, Girls",
    "Ice/Figure Skating",
    "Indoor Track, Boys",
    "Indoor Track, Girls",
    "Lacrosse, Boys",
    "Lacrosse, Girls",
    "Martial Arts",
    "Outdoor Track, Boys",
    "Outdoor Track, Girls",
    "Soccer, Boys",
    "Soccer, Girls",
    "Softball",
    "Swimming, Boys",
    "Swimming, Girls",
    "Tennis, Boys",
    "Tennis, Girls",
    "Ultimate Frisbee",
    "Volleyball, Boys",
    "Volleyball, Girls",
    "Wrestling"
]

const allClubsList = [
    "AHS Arcade",
    "American Red Cross Club",
    "American Sign Language Club",
    "Amnesty International Club",
    "Animal Advocacy Club",
    "Anime and Manga Club",
    "Anti - Food Insecurity Club",
    "Anti - Racism Working Group",
    "Arlington Science Training and Research(A STaR)",
    "Armenian Club",
    "Art and Photography Club",
    "Asian American Coalition",
    "Astronomy Club",
    "Badminton Club",
    "Bass After Class Fishing Club",
    "Best Buddies",
    "Bio - Med Club",
    "Black Student Union",
    "Board Game Club",
    "Book Club",
    "Boy Scouts",
    "Bridge Builders",
    "Bullet Journal Club",
    "Business Club",
    "Ceramics Club",
    "Chess Club",
    "Chinese Culture Club",
    "Comedy Club",
    "Compass Club",
    "Computer Club",
    "Creating Connections and Change in the APD",
    "Culinary Classes",
    "Current Crises Club",
    "Cycling Club(Biking Club)",
    "Employment",
    "Do Something and Interact Club",
    "Drama Guild",
    "Dungeons and Dragons(D & D) Club",
    "Faith Based Activities",
    "Finance Club",
    "Focus Media",
    "French Club",
    "Future Nurses Club",
    "Gardening Club",
    "Gilbert and Sullivan Club",
    "Girl Scouts",
    "Girl - Up",
    "Girls in STEM",
    "GSA(Gender and Sexuality Alliance)",
    "Half Marathon Club",
    "Health and Fitness Club",
    "Hiking Club",
    "History Club",
    "Intergenerational Book Club",
    "Japanese Culture Club",
    "Jewelry Making Club",
    "Journalism Club",
    "LARP(Live Action Role Play)",
    "Latin Club",
    "Literary Magazine",
    "Madrigals",
    "Marketing Club",
    "Math Club",
    "Mock Trial Team",
    "Model Congress",
    "Model UN",
    "Music / Instrument lessons",
    "Music Tech club",
    "National Honor Society",
    "Philosophy Club",
    "Ping Pong Club",
    "Pokemon Club",
    "Political Action Club",
    "Ponder Scope Club",
    "Prevention Allies Club",
    "Public Speaking",
    "Quiz Club",
    "Relay For Life Participant",
    "Religious Youth Group",
    "Robotics Club",
    "SAVE Club",
    "Save the Children",
    "Science Olympiad Club",
    "Scoopermania Club",
    "SEGA Club",
    "Self - Love and Positivity Club",
    "Ski Club",
    "Spanish Club",
    "Speech and Debate Club",
    "STEAM Club",
    "String Orchestra",
    "Student Library Advisory Committee",
    "Studio / Fine Art ",
    "Sustainability Club",
    "Symphonic / Jazz Band",
    "Ukulele Club",
    "Ultimate Frisbee Club",
    "Veg Club",
    "Women's Health Club",
    "XC Ski Club",
    "Yearbook",
    "Young Americans",
    "Young Feminist Alliance(YFA)",
    "Young Progressive"
]

const allIntendedCareerList = [
    "Accounting",
    "Anthropology",
    "Architecture",
    "Astronomy",
    "Astrophysics",
    "Biomedical Fields",
    "Business",
    "Communications",
    "Computer Engineering",
    "Computer Science",
    "Criminal Justice/Law Enforcement",
    "Drama",
    "Data Science",
    "Digital Design",
    "Education - Early Childhood",
    "Education – Elementary",
    "Education - Secondary",
    "Education – Special Ed",
    "Electrical & Computer Engineering",
    "Engineering any",
    "Engineering Mechanical",
    "English/Creative Writing/Journalism",
    "Environmental Science",
    "Fashion Design",
    "Film Production/Animation",
    "Finance",
    "Fine Art",
    "Health Fields Undecided",
    "Health Science",
    "History/Social Science",
    "Interactive Media Design/ Video Game Design",
    "International Development Studies",
    "International Business",
    "International/Global Politics",
    "International Relations",
    "Information Technology",
    "Journalist",
    "Kinesiology",
    "Marketing",
    "Mathematics",
    "Modern & World Languages",
    "Music/Sound/Recording",
    "Neuroscience",
    "Nursing",
    "Performing Arts",
    "Pharmacy",
    "Photography",
    "Physical Therapy",
    "Physiology",
    "Political Science",
    "Pre-Dental",
    "Pre-Law",
    "Pre-Med",
    "Psychology",
    "Public Health",
    "Occupational Therapy",
    "Religious Studies",
    "Sociologist",
    "Sports Management",
    "Sports Management/Communication",
    "Statistics/Data Science",
    "Studio Art",
    "Theatre",
    "Urban Planning",
    "Undecided",
    "None of the Above",
]

const allMajorsList = [
    "Accounting",
    "Anthropology",
    "Architecture",
    "Astronomy",
    "Astrophysics",
    "Biomedical Fields",
    "Business Includes",
    "Communications",
    "Computer Science",
    "Computer Engineering",
    "Criminal Justice/Law Enforcement",
    "Drama",
    "Data Science and Environmental Science",
    "Digital Design",
    "Education - Early Childhood",
    "Education – Elementary",
    "Education - Secondary",
    "Education – Special Ed",
    "Electrical & Computer Engineering",
    "Engineering any",
    "Engineering Mechanical",
    "English/Creative Writing/Journalism",
    "Environment",
    "Environmental Science.",
    "Fashion Design",
    "Film Production/Animation",
    "Finance",
    "Fine Art",
    "Health Fields Undecided",
    "Health Science",
    "History/Social Science",
    "Interactive Media Design/ Video Game Design",
    "Information Technology",
    "International Business",
    "International Development Studies",
    "International/Global Politics",
    "International Relations",
    "Kinesiology",
    "Languages Modern",
    "Marketing",
    "Mathematics",
    "Modern & World Languages",
    "Music",
    "Music/Sound/Recording",
    "Neuroscience",
    "Nursing",
    "Performing Arts",
    "Pharmacy",
    "Photography",
    "Physical Therapy/Occupational Therapy",
    "Physiology",
    "Political Science",
    "Pre-Dental",
    "Pre-Law",
    "Pre-Med",
    "Psychology",
    "Psychology",
    "Public Health",
    "Religious Studies",
    "Sports Communication",
    "Sports Management",
    "Sociology",
    "Statistics/Data Science",
    "Studio Art",
    "Theatre",
    "Urban Planning",
    "Undecided",
    "None of the Above",
]

const postGradPlansList = [
    "2 year college",
    "4 year college",
    "Military",
    "Trade School",
    "Post-Grad School",
    "Employment",
    "Gap Year",
    "Undecided",
    "Other",
]
